
package ru.grakhell.oauthlib.model;

import com.squareup.moshi.Json;

//Autogenerated

public class App {

    @Json(name = "url")
    private String url;
    @Json(name = "name")
    private String name;
    @Json(name = "client_id")
    private String clientId;

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getClientId() {
        return clientId;
    }

    public void setClientId(String clientId) {
        this.clientId = clientId;
    }

}
