package ru.grakhell.oauthlib.model;

import java.util.List;
import com.squareup.moshi.Json;

//Autogenerated

public class Response {

    @Json(name = "id")
    private Integer id;
    @Json(name = "scopes")
    private List<String> scopes = null;
    @Json(name = "token")
    private String token;
    @Json(name = "token_last_eight")
    private String tokenLastEight;
    @Json(name = "hashed_token")
    private String hashedToken;
    @Json(name = "note")
    private String note;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public List<String> getScopes() {
        return scopes;
    }

    public void setScopes(List<String> scopes) {
        this.scopes = scopes;
    }

    public String getToken() {
        return token;
    }

    public void setToken(String token) {
        this.token = token;
    }

    public String getTokenLastEight() {
        return tokenLastEight;
    }

    public void setTokenLastEight(String tokenLastEight) {
        this.tokenLastEight = tokenLastEight;
    }

    public String getHashedToken() {
        return hashedToken;
    }

    public void setHashedToken(String hashedToken) {
        this.hashedToken = hashedToken;
    }


    public String getNote() {
        return note;
    }

    public void setNote(String note) {
        this.note = note;
    }

}
